language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
install:
  - pip install coveralls pep8 pep257 restructuredtext_lint
  - python setup.py install
script:
  - python setup.py test
  - pep8 --ignore=E501 resync-stats resync_tools tests
  - pep257 resync-stats resync_tools
  - rst-lint README
  - coverage run --source=resync_tools setup.py test
after_success:
  - coveralls