#!/usr/bin/env python

from resync.resource_list import ResourceList
import matplotlib.pyplot as plt
import math

def get_data0():
    return([0,1,2,3,3,4,4,4,4,5,6,7,10])

def get_data1():
    uri = raw_input("Resource List URI ? ")
    rl = ResourceList()
    rl.read(uri)
    print "Got %d entries" % len(rl)
    lengths = []
    lengths_no_zero = []
    no_length = 0
    for r in rl:
        if (r.length is not None):
            l = r.length / 1000.0
            lengths.append(l)
            if (l>0):
                lengths_no_zero.append(math.log10(l))
        else:
            no_length+=1
    print "%d resources have no length information" % (no_length)
    return(lengths, lengths_no_zero)

save_as = None
#save_as = 'hist.pdf'
(d,dnz) = get_data1()
#print d
fig = plt.figure()
f1 = fig.add_subplot(1,2,1)
f1.hist(d, bins=100)
f1.set_title('Histogram of resource sizes')
f1.set_xlabel('Size (kB)')
f1.set_ylabel('Number of resources')
f2 = fig.add_subplot(1,2,2)
f2.hist(dnz, bins=100)
f2.set_title('Histogram of log10(resource sizes)')
f2.set_xlabel('log10( Size (kB) )')
f2.set_ylabel('Number of resources')
if (save_as):
    plt.savefig(save_as, format='pdf', orientation='landscape')
else:
    plt.show()
